version: '3'

services:
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - /c/mongodb:/data/db
    networks:
      - mongo-compose-network
    restart: always

  mongo-express:
    container_name: mongo-express-dev
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN : 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo-dev
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - mongo-compose-network  
    restart: always
  
  radix-event:
    container_name: radix-event-api
    image: ronaldoribeirojr/images:radix_event
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      MONGO_CONNECTION: mongodb://root:mongo@mongo-dev:27017
      MONGO_DATABASE_NAME: radixDB
      SENSOR_EVENT_COLLETION: sensorEvents
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - mongo-compose-network  
    restart: always

networks: 
    mongo-compose-network:
      driver: bridge